### ISSUE TITLE
接入最新的SDK

### ISSUE THREAD

**Issue by ainiyiwan** [rongcloud/demo-app-imlib-live-chatroom-android#7]
03-07 15:24:06.910 23525-23525/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: cn.rongcloud.live, PID: 23525
                                                   java.lang.NoClassDefFoundError: Failed resolution of: Lio/rong/push/PushService;
                                                       at io.rong.push.RongPushClient.init(RongPushClient.java:146)
                                                       at io.rong.imlib.RongIMClient.initSDK(RongIMClient.java:508)
                                                       at io.rong.imlib.RongIMClient.init(RongIMClient.java:538)
                                                       at cn.rongcloud.live.LiveKit.init(LiveKit.java:84)
                                                       at cn.rongcloud.live.App.onCreate(App.java:16)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1028)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5730)
                                                       at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1640)
                                                       at android.os.Handler.dispatchMessage(Handler.java:105)
                                                       at android.os.Looper.loop(Looper.java:156)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6595)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
                                                    Caused by: java.lang.ClassNotFoundException: io.rong.push.PushService
                                                       at java.lang.VMClassLoader.findLoadedClass(Native Method)
                                                       at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                       at io.rong.push.RongPushClient.init(RongPushClient.java:146) 
                                                       at io.rong.imlib.RongIMClient.initSDK(RongIMClient.java:508) 
                                                       at io.rong.imlib.RongIMClient.init(RongIMClient.java:538) 
                                                       at cn.rongcloud.live.LiveKit.init(LiveKit.java:84) 
                                                       at cn.rongcloud.live.App.onCreate(App.java:16) 
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1028) 
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5730) 
                                                       at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1640) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                       at android.os.Looper.loop(Looper.java:156) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6595) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
                                                    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/JobIntentService;
                                                       at io.rong.push.RongPushClient.init(RongPushClient.java:146) 
                                                       at io.rong.imlib.RongIMClient.initSDK(RongIMClient.java:508) 
                                                       at io.rong.imlib.RongIMClient.init(RongIMClient.java:538) 
                                                       at cn.rongcloud.live.LiveKit.init(LiveKit.java:84) 
                                                       at cn.rongcloud.live.App.onCreate(App.java:16) 
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1028) 
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5730) 
                                                       at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1640) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                       at android.os.Looper.loop(Looper.java:156) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6595) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.JobIntentService" on path: DexPathList[[zip file "/data/app/cn.rongcloud.live-1/base.apk"],nativeLibraryDirectories=[/data/app/cn.rongcloud.live-1/lib/arm, /data/app/cn.rongcloud.live-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/vendor/lib]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                       at io.rong.push.RongPushClient.init(RongPushClient.java:146) 
                                                       at io.rong.imlib.RongIMClient.initSDK(RongIMClient.java:508) 
                                                       at io.rong.imlib.RongIMClient.init(RongIMClient.java:538) 
                                                       at cn.rongcloud.live.LiveKit.init(LiveKit.java:84) 
                                                       at cn.rongcloud.live.App.onCreate(App.java:16) 
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1028) 
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5730) 
                                                       at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1640) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                       at android.os.Looper.loop(Looper.java:156) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6595) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by ainiyiwan** [comment]
已解决，SDK>23
